name: hero
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  supabase_flutter: ^2.3.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^13.0.0
  shimmer: ^3.0.0
  dio: ^5.4.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  dynamic_height_list_view:


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.4.2
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/.env